
title: "LiteG | Magisk Module | Tweaks For User Experience"

baseurl: "/"
url: "https://litegapps.github.io"
twitter_username: liteg
github_username:  liteg
author: LiteG

plugins:

  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
