
title: LiteGapps
email: litegapps@gmail.com
description: "The LiteGapps Project Official Website"
baseurl: "/"
url: "https://litegapps.github.io"
twitter_username: litegapps
github_username:  litegapps
author: LiteGapps

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
