
title: LiteG
email: LiteG@gmail.com
description: "LiteG Official Website"
baseurl: "/"
url: "https://litegapps.github.io"
twitter_username: liteg
github_username:  liteg
author: LiteG

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
