baseurl = "https://litegapps.github.io"
title = "LiteGapps - Custom Google Apps Android"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en"
resourceDir = "../resources"
DefaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle      = "monokai"

[markup.goldmark.renderer]
  unsafe = true # agar bisa menulis html di markdown
  
buildFuture = true

[pagination]
  disableAliases = false
  pagerSize = 19
     
[sitemap]
  changefreq = "always"
  priority = 0.8
  filename = "sitemap.xml"
[permalinks]
   changelog     = ":section/:year/:slug"
  
[params]
  author = "The LiteGapps Project"
  description = "LiteGapps is a custom Google Apps on the Android operating system, an open source project that focuses on small, efficient, and comprehensive."
  recent_posts_number = 3

[outputs.taxonomy.removePath]
  tags = ["/tags"]
  categories = ["/categories"]
  
  